config/routes.rb
Rails.application.routes.draw do
  resources :buildings do
    member do
      post 'increment_level'
      post 'upto_level'
    end
  end
  resources :planets
  resources :players do
    member do
      get 'advisor'
      get 'building_advisor'
      get 'research_advisor'
      get 'artillery_advisor'
    end
  end
  resources :researches do
    member do
      post 'increment_level'
      post 'upto_level'
    end
  end

  root to: 'players#index'
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :player
  has_many :buildings do
    include BlueprintScopes
    include EffectScopes

    def where_effect(effect)
      super.includes(:planet, player: {researches: :blueprint})
    end
  end
  has_many :blueprints, through: :buildings

  def self.[] value
    find_by(name: value)
  end

  delegate :costs, :cumulative_costs, :produces, :stocks, to: :buildings

  # def update_ressources_since_last_production!
  #   now = Time.now
  #   update_ressources! produces_in(time: now - last_production)
  #   update! last_production: now
  # end
  #
  # def update_ressources!(ressources)
  #   update! holds.merge(ressources, &merge_proc(:+))
  # end
  #
  # def produces_in time:
  #   produces
  #     .slice(:metal, :cristal, :deuterium)
  #     .each_with_object({}) do |(ressource, value), acc|
  #       acc[ressource] = [
  #         value * time / 3600,
  #         [
  #           stocks[ressource] - holds[ressource],
  #           0,
  #         ].max,
  #       ].min
  #     end
  # end

  # def ressources
  #   holds.each_with_object({}) do |(ressource, hold), acc|
  #     acc[ressource] = {
  #       holds: hold,
  #       produces: produces[ressource],
  #       stocks: stocks[ressource],
  #     }
  #   end
  # end

  # def holds
  #   attributes
  #     .slice(*%w[metal cristal deuterium])
  #     .map{ |k, v| [k.to_sym, v] }
  #     .to_h
  # end

  # def energy_efficiency(extra_consumption: 0)
  #   if produces[:energy] > extra_consumption
  #     1.0
  #   else
  #     energy_production = buildings.where_name(['solar_plant', 'fusion_plant']).produces[:energy]
  #     energy_consumption = energy_production - produces[:energy] + extra_consumption
  #     energy_production / energy_consumption
  #   end
  # end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def create
    planet = Planet.create planet_params
    Blueprint.where('name ~* ?', /^((?!tech|rocket).)*$/.source).each do |blueprint|
      planet.buildings.create(blueprint: blueprint, level: 0)
    end
    redirect_to planet.player
  end

  def edit
    render :edit, locals: {planet: find_planet}
  end

  def update
    planet = find_planet
    planet.update! planet_params

    planet.buildings.includes(:blueprint).each do |building|
      building.update level: params[building.blueprint.name].to_i
    end

    redirect_to planet.player
  end

  def find_planet
    Planet.find_by id: params[:id]
  end

  def planet_params
    params.require(:planet).permit(:player_id, :name, :temperature, :size)
  end
end

app/views/planets/_planet.slim
.planet
  h3 = planet.name
  p = link_to 'Éditer', edit_planet_path(planet)
  
  / = render partial: "buildings_size", locals: {planet: planet}
  = render partial: "builds", locals: {planet: planet, player: player}

app/views/planets/edit.slim
#edit-planet
  #ships
    #ship-1 = link_to player_path(planet.player) do
      = render partial: 'ships/model-C'
  
  h1 
    span = planet.name
    
  = form_with model: planet do |f|
    .floating-input
      = f.text_field :name, placeholder: "Nom de la planète (ex: PT1)"
      = f.label :name, "Nom"
      
    .floating-input
      = f.number_field :size, placeholder: "Nombre de cases de la planète (ex: 193)"
      = f.label :size, "Taille"
    
    .floating-input
      = f.number_field :temperature, placeholder: "Température maximale sur la planète (ex: 81)"
      = f.label :temperature, "Température"
      
    hr
    
    - planet.buildings.order(:id).includes(:blueprint).each do |building|
      .floating-input
        - if building.level.zero?
          = number_field_tag building.blueprint.name, nil, placeholder: "Niveau du batiment #{ building.blueprint.name.humanize } (ex: 12)"
        - else
          = number_field_tag building.blueprint.name, building.level, placeholder: "Niveau du batiment #{ building.blueprint.name.humanize } (ex: 12)"
        = f.label building.blueprint.name, building.blueprint.name.humanize
    
    = f.submit "Mettre à jour"