config/routes.rb
Rails.application.routes.draw do
  resources :buildings do
    member do
      post 'increment_level'
      post 'upto_level'
    end
  end
  resources :planets
  resources :players do
    member do
      get 'advisor'
      get 'building_advisor'
      get 'research_advisor'
      get 'artillery_advisor'
    end
  end
  resources :researches do
    member do
      post 'increment_level'
      post 'upto_level'
    end
  end

  root to: 'players#index'
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :planets
  has_many :buildings, through: :planets do
    include BlueprintScopes
    include EffectScopes

    def where_effect(effect)
      super.includes(:planet, player: {researches: :blueprint})
    end
  end
  has_many :researches do
    include BlueprintScopes
    include EffectScopes
  end

  # def advisor
  #   @advisor ||= Advisor.new(self)
  # end

  def production_advisor
    @production_advisor ||= ProductionAdvisor.new(self)
  end

  def energy_advisor
    @energy_advisor ||= EnergyAdvisor.new(self)
  end

  def artillery_advisor
    @artillery_advisor ||= ArtilleryAdvisor.new(self)
  end

  def costs **options
    effects(effect: :costs, **options)
  end

  def cumulative_costs **options
    effects(effect: :cumulative_costs, **options)
  end

  def produces **options
    effects(effect: :produces, **options)
  end

  def sustains **options
    effects(effect: :sustains, **options)
  end

  def cumulative_sustains **options
    effects(effect: :cumulative_sustains, **options)
  end

  # def holds **options
  #   effects(effect: :holds, **options)
  # end

  def effects **options
    @effects ||= Hash.new do |hash, key|
      hash[key] = compute_effects(**key)
    end
    @effects[options]
  end

  def compute_effects effect:, **options
    buildings.send(effect, **options).merge(researches.send(effect, **options), &merge_proc(:+))
  end

  # def ressources
  #   effect(effect: :ressources)
  # end

  # def holds
  #   effect(effect: :holds)
  # end

  # def effect effect:
  #   planets
  #     .map(&effect.to_proc)
  #     .inject({}) do |effect, effect_building|
  #       effect.deep_merge(effect_building, &merge_proc(:+))
  #     end
  # end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    render :index, locals: {players: Player.all}
  end

  def create
    player = Player.create player_params
    planet = player.planets.create(name: "Planète mére", temperature: 81, size: 193)
    Blueprint.where('name ~* ?', /^.*_tech$/.source).each do |blueprint|
      player.researches.create(blueprint: blueprint, level: 0)
    end
    Blueprint.where('name ~* ?', /^((?!tech|rocket).)*$/.source).each do |blueprint|
      planet.buildings.create(blueprint: blueprint, level: 0)
    end

    redirect_to player
  end

  def show
    render :show, locals: {player: find_player}
  end

  def edit
    render :edit, locals: {player: find_player}
  end

  def update
    player = find_player
    player.update! player_params

    player.researches.includes(:blueprint).each do |research|
      research.update level: params[research.blueprint.name].to_i
    end

    redirect_to player
  end

  # def advisor
  #   @player = find_player
  #   @advisor = Advisor.new(@player)
  # end
  #
  # def building_advisor
  #   @player = find_player
  #   @advisor = BuildingAdvisor.new(@player)
  #   render :advisor
  # end
  #
  # def research_advisor
  #   @player = find_player
  #   @advisor = ResearchAdvisor.new(@player)
  #   render :advisor
  # end
  #
  # def artillery_advisor
  #   @player = find_player
  #   @advisor = ArtilleryAdvisor.new(@player)
  #   render :advisor
  # end

  def find_player
    Player
      .includes(
        planets: {buildings: :blueprint},
        researches: :blueprint
      )
      .find_by(id: params[:id])
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/views/players/_best_builds.slim
#best-builds
  = render partial: "build", locals: {build: player.production_advisor.best_build, include_planet: true}
  hr
  = render partial: "build", locals: {build: player.energy_advisor.best_build, include_planet: true}
  hr
  = render partial: "build", locals: {build: player.artillery_advisor.best_build, include_planet: true}
  
  
  / 
  / = render partial: "best_build", locals: {build: player.production_advisor.best_build}
  / - if player.energy_advisor.best_build
  /   hr
  /   = render partial: "best_build", locals: {build: player.energy_advisor.best_build}
  
  / hr
  / #best-research
  /   h3 = research[:planet].name
  /   p = research[:buildings].first.blueprint.name.humanize
  /   .index
  /     .bar[style="width: #{ research[:percentage_index] * 100 }%"]
  /   = form_with url: upto_level_research_path(research[:buildings].first) do |f|
  /     = hidden_field_tag :upto, research[:upto]
  /     = hidden_field_tag :planet_id, research[:planet].id
  /     = f.submit "Rechercher le niveau #{ research[:upto] }"

app/views/players/_build.slim
- include_planet ||= false
- include_percentage ||= false

.building-build[class="#{"danger" if build.warnings.present?}"]
  - if include_planet
    h3 = build.planet.name
  p = build.building.blueprint.name.humanize
  .index
    - if include_percentage
      | #{ (build.percentage * 100).round(1) }%
    .bar[style="width: #{ build.percentage * 100 }%"]
      - if include_percentage
        span #{ (build.percentage * 100).round(1) }%
  - if build.type == :tech
    = form_with url: upto_level_research_path(build.building) do |f|
      = hidden_field_tag :upto, build.upto
      = hidden_field_tag :planet_id, build.planet.id
      = f.submit "Rechercher le niveau #{ "%02d" % build.upto.to_i }"
  - elsif build.type == :artillery
    = form_with url: upto_level_building_path(build.building) do |f|
      = hidden_field_tag :upto, build.upto
      = f.submit "Contruire #{ "%02d" % (build.increment) } supplémentaire"
  - else
    = form_with url: upto_level_building_path(build.building) do |f|
      = hidden_field_tag :upto, build.upto
      = f.submit "Construire le niveau #{ "%02d" % build.upto.to_i }"

app/views/players/_buildings_size.slim
.buildings-size
  - metal_size = planet.buildings.where_name(['metal_mine', 'metal_storage']).map(&:level).inject(0, &:+) / planet.size.to_f
  - cristal_size = planet.buildings.where_name(['cristal_mine', 'cristal_storage']).map(&:level).inject(0, &:+) / planet.size.to_f
  - deuterium_size = planet.buildings.where_name(['deuterium_mine', 'deuterium_storage']).map(&:level).inject(0, &:+) / planet.size.to_f
  - energy_size = planet.buildings.where_name(['solar_plant', 'fusion_plant']).map(&:level).inject(0, &:+) / planet.size.to_f
  - factory_size = planet.buildings.where_name(/^.*_factory$/).map(&:level).inject(0, &:+) / planet.size.to_f
  - max_size = [metal_size, cristal_size, deuterium_size, energy_size, factory_size].max * 1.5
  
  .metal-mine[style="width: #{ 100 * metal_size }%; border-bottom-width: #{ metal_size / max_size }em"]
  .cristal-mine[style="width: #{ 100 * cristal_size }%; border-bottom-width: #{ cristal_size / max_size }em"]
  .deuterium-mine[style="width: #{ 100 * deuterium_size }%; border-bottom-width: #{ deuterium_size / max_size }em"]
  .energy-plants[style="width: #{ 100 * energy_size }%; border-bottom-width: #{ energy_size / max_size }em"]
  .factories[style="width: #{ 100 * factory_size }%; border-bottom-width: #{ factory_size / max_size }em"]

app/views/players/_builds.slim
.builds
  .buildings
    = render partial: "build", collection: player.production_advisor.build_list_by(planet: planet), locals: {include_percentage: true}
    hr
    = render partial: "build", collection: player.energy_advisor.build_list_by(planet: planet), locals: {include_percentage: true}
    hr
    = render partial: "build", collection: player.artillery_advisor.build_list_by(planet: planet), locals: {include_percentage: true}
    
  / - researches = advisor \
  /     .build_list \
  /     .select { |build| build[:planet] == planet && build[:type] == :research }
  / - if researches.present?
  /   hr
  /   .researches
  /     - researches.each do |build|
  /       .research-build
  /         p = build[:buildings].first.blueprint.name.humanize
  /         .index
  /           | #{ (build[:percentage_index] * 100).round(1) }%
  /           .bar[style="width: #{ build[:percentage_index] * 100 }%"]
  /             span #{ (build[:percentage_index] * 100).round(1) }%
  /         = form_with url: upto_level_research_path(build[:buildings].first) do |f|
  /           = hidden_field_tag :upto, build[:upto]
  /           = hidden_field_tag :planet_id, build[:planet].id
  /           = f.submit "Rechercher le niveau #{ build[:upto] }"

app/views/players/_player.slim
li.player = link_to "Jouer en tant que #{player.name}", player_path(player)

app/views/players/_production_ratio.slim
#production-ratio
  - metal_percent = [advisor.ideal_ratio[:metal], advisor.actual_ratio[:metal]].min
  - cristal_percent = [advisor.ideal_ratio[:cristal], advisor.actual_ratio[:cristal]].min
  - deuterium_percent = [advisor.ideal_ratio[:deuterium], advisor.actual_ratio[:deuterium]].min
  - total_produces = player.produces.slice(:metal, :cristal, :deuterium).values.inject(0, &:+)
  
  #metal[style="width: #{metal_percent * 100}%"] = sprintf("%+d", advisor.differential_ratio[:metal] * total_produces)
  #metal-difference[style="width: #{advisor.differential_ratio[:metal].abs * 100}%"]

  #cristal[style="width: #{cristal_percent * 100}%"] = sprintf("%+d", advisor.differential_ratio[:cristal] * total_produces)
  #cristal-difference[style="width: #{advisor.differential_ratio[:cristal].abs * 100}%"]
  
  #deuterium[style="width: #{deuterium_percent * 100}%"] = sprintf("%+d", advisor.differential_ratio[:deuterium] * total_produces)

app/views/players/advisor.slim
h3 = link_to @player.name, player_path(@player)

p = @advisor.differential_ratio

- @advisor.call.each do |build|
  ul
    li = build[:planet].name
    li = build[:buildings].map{|building| building.blueprint.name}
    li = build[:buildings].map(&:level)
    li = build[:time_index]
    li = build[:ratio_index]
    li = build[:percentage_index]
    - costs = build[:buildings].first.costs(modifiers: {level: 1})
    li M-#{ number_with_delimiter(costs[:metal].to_i, delimiter: ".") }
    li C-#{ number_with_delimiter(costs[:cristal].to_i, delimiter: ".") }
    li D-#{ number_with_delimiter(costs[:deuterium].to_i, delimiter: ".") }
    li 
      - case build[:type]
      - when :artillery
        = form_with url: increment_level_building_path(build[:buildings].first) do |f|
          = f.label :increment, "(#{build[:upto] - build[:buildings].first.level} needed)"
          = f.text_field :increment
          = f.submit "Build"
        | or
        = form_with url: increment_level_building_path(build[:buildings].first) do |f|
          = hidden_field_tag :increment, build[:upto] - build[:buildings].first.level
          = f.submit "Build #{build[:upto] - build[:buildings].first.level}"
      - when :building
        = form_with url: upto_level_building_path(build[:buildings].first) do |f|
          = hidden_field_tag :upto, build[:upto]
          = f.submit "Build level #{ build[:upto] }"
      - when :research
        = form_with url: upto_level_research_path(build[:buildings].first) do |f|
          = hidden_field_tag :upto, build[:upto]
          = hidden_field_tag :planet_id, build[:planet].id
          = f.submit "Research level #{ build[:upto] }"

app/views/players/edit.slim
#edit-player
  #ships
    #ship-1 = link_to player do
      = render partial: 'ships/model-C'
  
  h1 
    span = player.name
    
  = form_with model: player do |f|
    .floating-input
      = f.text_field :name, placeholder: "Nom du joueur (ex: Petrochou)"
      = f.label :name, "Nom"
      
    hr
    
    - player.researches.order(:id).includes(:blueprint).each do |research|
      .floating-input
        - if research.level.zero?
          = number_field_tag research.blueprint.name, nil, placeholder: "Niveau de la recherche #{ research.blueprint.name.humanize } (ex: 5)"
        - else
          = number_field_tag research.blueprint.name, research.level, placeholder: "Niveau de la recherche #{ research.blueprint.name.humanize } (ex: 5)"
        = f.label research.blueprint.name, research.blueprint.name.humanize
    
    = f.submit "Mettre à jour"

app/views/players/index.slim
#players
  #ships
    #ship-1 = render partial: 'ships/model-C'
    #ship-2 = render partial: 'ships/model-C'
    #ship-3 = render partial: 'ships/model-B'

  h1 
    span Ogame<br>Advisor
   
  ul#players-list = render players 
  
  #new-player
    h3 Ou
    
    = form_with model: Player.new, html: {autocomplete: "off"} do |f|
      .floating-input
        = f.text_field :name, placeholder: "Nom du joueur (ex: Petrochou)"
        = f.label :name, "Nom"
      
      = f.submit "Créez un nouveau joueur"

app/views/players/show.slim
#player
  #ships
    #ship-1 = link_to players_path do
      = render partial: 'ships/model-B'
    
    #ship-2 = link_to edit_player_path(player) do
      = render partial: 'ships/model-C'
  
  h1 
    span = player.name
    
  = render partial: 'production_ratio', locals: {player: player, advisor: player.production_advisor}
  = render partial: 'best_builds', locals: {player: player}
  
  ul#planets-list = render player.planets.sort_by(&:id), player: player
    
  #new-planet
    h3 Coloniser une nouvelle planète
    
    = form_with model: player.planets.build, html: {autocomplete: "off"} do |f|
      = f.hidden_field :player_id
      
      .floating-input
        = f.text_field :name, placeholder: "Nom de la planète (ex: PT1)"
        = f.label :name, "Nom"
      
      .floating-input
        = f.number_field :size, placeholder: "Nombre de cases de la planète (ex: 193)"
        = f.label :size, "Taille"
        
      .floating-input
        = f.number_field :temperature, placeholder: "Température maximale sur la planète (ex: 81)"
        = f.label :temperature, "Température"
        
      = f.submit "Créez une nouvelle planète"

/ 
/ h3 = @player.name
/ 
/ p = link_to "Advisor", advisor_player_path(@player)
/ p = link_to "Building Advisor", building_advisor_player_path(@player)
/ p = link_to "Research Advisor", research_advisor_player_path(@player)
/ p = link_to "Artillery Advisor", artillery_advisor_player_path(@player)
/ 
/ .ressources
/   - @player.ressources.each do |(ressource, values)|
/     div class=ressource
/       span.holds = number_with_delimiter values[:holds].to_i
/       span.produces = number_with_delimiter values[:produces].to_i
/       span.stocks = number_with_delimiter values[:stocks].to_i
/ 
/ - @player.planets.sort_by(&:id).each do |planet|
/   h3 = planet.name
/   - planet.ressources.each do |(ressource, values)|
/     div class=ressource
/       span.holds = number_with_delimiter values[:holds].to_i
/       span.produces = number_with_delimiter values[:produces].to_i
/       span.stocks = number_with_delimiter values[:stocks].to_i
/   div class='energy'
/     span.produces = number_with_delimiter planet.produces[:energy].to_i
/ 
/   = form_with model: planet do |f|
/     = f.text_field :metal
/     = f.text_field :cristal
/     = f.text_field :deuterium
/     = f.submit "Update ressources"
/ 
/   table
/     tr
/       - planet.buildings.sort_by(&:id).each do |building|
/         td
/           p = building.blueprint.name
/           p = building.level
/           = form_with url: increment_level_building_path(building) do |f|
/             = hidden_field_tag :increment, 1
/             = f.submit "Update to level #{ building.level + 1 }"
/ 
/   table
/     tr
/       - @player.researches.sort_by(&:id).each do |research|
/         td
/           p = research.blueprint.name
/           p = research.level
/           = form_with url: increment_level_research_path(research) do |f|
/             = hidden_field_tag :increment, 1
/             = hidden_field_tag :planet_id, planet.id
/             = f.submit "Update to level #{ research.level + 1 }"
/ 
/ = form_with model: @player.planets.build do |f|
/   = f.hidden_field :player_id
/   = f.text_field :name
/   = f.number_field :temperature
/   = f.submit "Create"